### ISSUE TITLE
Input Checker Enhancements

### ISSUE THREAD

**Issue by dhensle** [ActivitySim/activitysim#894]
Consolidation of issues around input checker enhancements:

- [ ] Pydantic settings validation (#785)
- [ ] coefficients and spec file syntax checking (#616)
- [ ] More general skim data checks (#873)

General theme is we want ActivitySim to crash early for both data _and_ configuration issues.

**Comment by dhensle** [comment]
Closed in favor of the other tasks
